version: "3.8"
services:
    jenkins:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: jenkins
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - ~/.ssh:/var/jenkins_home/.ssh
        environment:
            - DOCKER_HOST=unix:///var/run/docker.sock
        restart: unless-stopped

    docker-dind:
        image: docker:dind
        container_name: jenkins-docker
        privileged: true
        volumes:
            - jenkins_docker_certs:/certs/client
            - jenkins_home:/var/jenkins_home
        environment:
            - DOCKER_TLS_CERTDIR=/certs

volumes:
    jenkins_home:
    jenkins_docker_certs:
